// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ISQMVa4guyyQkP4inUfRttt0wQpC8BY',
    appId: '1:562672075206:web:fbeae29b8e80c6086b32c7',
    messagingSenderId: '562672075206',
    projectId: 'curso-flutter-avanzado-23794',
    authDomain: 'curso-flutter-avanzado-23794.firebaseapp.com',
    storageBucket: 'curso-flutter-avanzado-23794.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVjkYmlqPbwB_I_V0M578uyRv5OoMWxf8',
    appId: '1:562672075206:android:cda10647c303f6196b32c7',
    messagingSenderId: '562672075206',
    projectId: 'curso-flutter-avanzado-23794',
    storageBucket: 'curso-flutter-avanzado-23794.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjvoKGuMd4EZBgkmAjOtWr_27gMjkbff8',
    appId: '1:562672075206:ios:2cc4dda3278a04246b32c7',
    messagingSenderId: '562672075206',
    projectId: 'curso-flutter-avanzado-23794',
    storageBucket: 'curso-flutter-avanzado-23794.appspot.com',
    iosClientId:
        '562672075206-sdrn2l7q5k776pbkjd27fab79q7ooikf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjvoKGuMd4EZBgkmAjOtWr_27gMjkbff8',
    appId: '1:562672075206:ios:2cc4dda3278a04246b32c7',
    messagingSenderId: '562672075206',
    projectId: 'curso-flutter-avanzado-23794',
    storageBucket: 'curso-flutter-avanzado-23794.appspot.com',
    iosClientId:
        '562672075206-sdrn2l7q5k776pbkjd27fab79q7ooikf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
